### ISSUE TITLE
Feature Request: Charts for Timeseries

### ISSUE THREAD

**Issue by jacovinus** [metrico/cloki-view#41]
### Feature Request: Charts for Matrix type responses (timeseries)
**Problem to be solved**: 
Matrix type responses needs a propper visualization container.
As the type in question is timeseries, the most suitable solution should be charts.

**Solution**: 
After research found that the most suited package for this type of charts is the flot charts package and its plugins

**Features Inside Solution**:
1 -  Range Selection with auto submit new start and end times on query :heavy_check_mark: 
2 -  Enable / Disable Series Clicking on label  :heavy_check_mark: 
3 - Switch in between chart types (bars, lines, points)
4 - Tooltip hovering on points with data about the current series (label, timestamp, value),
5 - Auto Limit series amount (ideally 20)  :heavy_check_mark: 
6 - Button for showing all entries without the auto-limit  :heavy_check_mark: 

**Extra feature proposal** 
- add a `search/add labels` button (search icon) into each label for making a search from the labels inside the series label.

**Tasks Completed**
- 

- [x] Chart Visualization
- [x] Range Selection
- [x] Enable / Disable series
- [x] Switch in between chart types
- [x] Tooltip (needs to improve)
- [x] Auto Limit series
- [x] _Show all series_ button

**Comment by Dletta** [comment]
@jacovinus For some reason CTRL-Enter does not update the chart, only pushing "Show Logs" Button

**Comment by Dletta** [comment]
Actually it's sometimes query needs to be sent 2x to update chart
checking returns
Ah, hmm first time it does return the correct data (aka already updated) but chart is not immediately updated until I call it again
both CTRL-Enter or Show Logs Button

**Comment by jacovinus** [comment]
merged at #42 , closing
